//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgs.Persistance.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSession()
        {
            this.tbEtudiants = new HashSet<tbEtudiant>();
        }
    
        public int Id { get; set; }
        public string SessionId { get; set; }
        public int MaxInscription { get; set; }
        public int AnneeAcademique { get; set; }
        public string JoursCours { get; set; }
        public System.DateTime DateDebutCours { get; set; }
        public System.DateTime DateFinCours { get; set; }
        public int Session_Cours { get; set; }
        public int Session_Enseignant { get; set; }
    
        public virtual tbCour tbCour { get; set; }
        public virtual tbEnseignant tbEnseignant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEtudiant> tbEtudiants { get; set; }
    }
}
